services:
  backend:
    build: ./backend
    env_file:
      - .env
    container_name: backend_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/mydatabase
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis


  db:
    image: mysql:8.0
    container_name: backend_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: backend_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
